### ISSUE TITLE
Possible Monash theme improvements

### ISSUE THREAD

**Issue by eddelbuettel** [eddelbuettel/binb#12]
In no particular order:

- [x] add a vignette / demo _i.e._ something longer than the skeleton
- [x] document the options
- [x] make `monashwhite` the default?
- [x] make the defaults more sensible, _i.e._ currently several of the options in the yaml header in `skeleton.Rmd` (_e.g._ `fontsize`, `titlefontsize`, `compress`) are more or less mandatory
- [x] add `skeleton.Rmd` based demo to `README.md`, expand `README.md`
- [x] possible make `titlepage.png` the value of variable set in YAML to override default
- [x] more flexible font setup, maybe bera as fallback for carlito ?

Add more items as needed.

**Comment by eddelbuettel** [comment]
Just looking at this older issue -- @robjhyndman you hit most if not all of these out of the park, correct?

**Comment by eddelbuettel** [comment]
@robjhyndman We can probably close this now, no?  Looks like all the 'todos' above are now done?

**Comment by robjhyndman** [comment]
Yes, all done.
