### ISSUE TITLE
0.0.4 release

### ISSUE THREAD

**Issue by eddelbuettel** [eddelbuettel/binb#19]
We had a few nice PRs by @robjhyndman @jolars @jsta so the time may be right for a 0.0.4 rollup and release.  Any objections, anyone?   Paging @izahn and @robjhyndman in particular ...

**Comment by robjhyndman** [comment]
ok with me. I haven't time to look at https://github.com/eddelbuettel/binb/issues/12 in the next 2 weeks, but will do so after that.

**Comment by eddelbuettel** [comment]
No rush on #12 -- we have open tickmarks on all four themes.  The three of us should get back to that and clean up "one of these days".  It just looked to me as if your two PRs since the last release addressed some of the issues.

**Comment by eddelbuettel** [comment]
win-builder and my checks here like 0.0.4 so I may just roll it up and push it.

**Comment by eddelbuettel** [comment]
Done.
