### ISSUE TITLE
Presento ignores date set in YAML

### ISSUE THREAD

**Issue by Selbosh** [eddelbuettel/binb#21]
I am not entirely sure where the bug is, but it seems like no matter what we set as the `date` in the YAML header, Presento always prints the date as if it were `\today`. Even if we set it to `NULL` or an empty string `""`.

I had a quick look at the pandoc template but didn't spot anything obvious.

**Comment by eddelbuettel** [comment]
(First off, thanks for your other catch.  Will merge that soon, possibly tomorrow.)

I always have to sit down with a strong beverage when I chase these things as it could come from the R code, or the template, or the style.   But I agree that the YAML if set should prevail.

**Comment by Selbosh** [comment]
I found the problem in the line
```tex
\newcommand{\myDetails}{\setnote{\today}}
```
on https://github.com/eddelbuettel/binb/blob/27f4e058828f134251c264e6b737c662775ad58c/inst/rmarkdown/templates/presento/resources/template.tex#L252 which appears to be fixed already in the GitHub version thanks to https://github.com/eddelbuettel/binb/commit/d6d63bca4e88bb875acdc90cc453acf2b19beb45. I guess the CRAN edition doesn't have the fix yet.

**Comment by eddelbuettel** [comment]
Hah. I was grep'ing around in my sources not seeing anything ... that would explain why.

**Comment by eddelbuettel** [comment]
Hm, https://github.com/eddelbuettel/binb/commit/d6d63bca4e88bb875acdc90cc453acf2b19beb45 should have made it into 0.0.4 though. See this line from the NEWS.Rd:  
https://github.com/eddelbuettel/binb/blob/master/inst/NEWS.Rd#L15-L16

**Comment by Selbosh** [comment]
Hmmm, I was fairly sure I was using the latest Cran version, but maybe it hadn't pushed through to my mirror yet. In any case, I used `devtools::install_github` just now and can confirm 0.0.4 works fine, so will close this.
