### ISSUE TITLE
metropolis(citation_package) argument appears to have no default

### ISSUE THREAD

**Issue by f-edwards** [eddelbuettel/binb#29]
Receiving an error on previously working code when calling binb::metropolis in RMarkdown or directly in R:

> metropolis()
Error in match.arg(citation_package) : 'arg' must be of length 1

I'm unable to figure out how to pass an argument for citation_package="none" in the RMarkdown YAML header. Suspect it may be the default value for citation_package

The MWE in the readme for binb::metropolis does not work for me (R 4.02; binb_0.0.6)

**Comment by eddelbuettel** [comment]
That may be a side-effect of accomodating other users who asked for citation support.  At a minimum I could / should update the README.md (there is no file 'readme').

But I am having a bit of trouble with your issue ticket.  What is it you really want to do?   Nobody is calling the `metropolis()` function directly...

```sh
edd@rob:~/git/binb(master)$ mkdir quick-demo
edd@rob:~/git/binb(master)$ cd quick-demo/
edd@rob:~/git/binb/quick-demo(master)$ cp -vax ../inst/rmarkdown/templates/metropolis/skeleton/skeleton.Rmd .
'../inst/rmarkdown/templates/metropolis/skeleton/skeleton.Rmd' -> './skeleton.Rmd'
edd@rob:~/git/binb/quick-demo(master)$ render.r skeleton.Rmd      # simple rmarkdown::render() wrapper 
[....]
edd@rob:~/git/binb/quick-demo(master)$ ls -l skeleton.*
-rw-rw-r-- 1 edd edd 47534 Aug  7 11:22 skeleton.pdf
-rw-r--r-- 1 edd edd  2178 Sep 19  2018 skeleton.Rmd
edd@rob:~/git/binb/quick-demo(master)$ 
```

That suggests is still works.  (It is also my goto-personal md file for slides and I use it all the time myself....)

**Comment by f-edwards** [comment]
apologies for the confusion on README.md vs readme. I suppose a simple update to README.md that explains how to succesfully pass a citation_package = "none" argument through the YAML header in rmarkdown is what I'm looking for.

**Comment by eddelbuettel** [comment]
I am in the middle of something else.  

Maybe it defaults to `natbib` now.  Is that so deadly?  If you cite nothing there is reference sections etc pp.

**Comment by f-edwards** [comment]
No rush at all. There's no problem with a natbib default. I'm simply unable to knit the MWE, and I suspect it may be a problem with the default for citation_style:

---
title: A minimal example
author: Matthias Vogelgesang
date: \today
institute: Centre for Modern Beamer Themes
output: binb::metropolis
---

# First Section

## First Frame

Hello, world!

Error in match.arg(citation_package) : 'arg' must be of length 1
Calls: <Anonymous> ... create_output_format -> do.call -> <Anonymous> -> <Anonymous> -> match.arg
Execution halted

**Comment by eddelbuettel** [comment]
Works here:

```sh
edd@rob:~/git/binb/quick-demo(master)$ cat mwe.Rmd
---
title: A minimal example
author: Matthias Vogelgesang
date: \today
institute: Centre for Modern Beamer Themes
output: binb::metropolis
---

# First Section

## First Frame

Hello, world!
edd@rob:~/git/binb/quick-demo(master)$ Rscript -e 'rmarkdown::render("mwe.Rmd")'


processing file: mwe.Rmd
  |..............................................................................................................................................................................................| 100%
  ordinary text without R code


output file: mwe.knit.md

/home/edd/bin/pandoc +RTS -K512m -RTS mwe.utf8.md --to beamer --from markdown+autolink_bare_uris+tex_math_single_backslash --output mwe.tex --template /usr/local/lib/R/site-library/binb/rmarkdown/templates/metropolis/resources/template.tex --slide-level 2 --variable theme=metropolis --highlight-style tango --pdf-engine xelatex --self-contained 

Output created: mwe.pdf
edd@rob:~/git/binb/quick-demo(master)$ 
```

What platform / OS / pandoc version / ... do you have?  Ubuntu 20.04 here.

**Comment by f-edwards** [comment]
It's MacOS 10.15.6 / latest pandoc. I can get it to compile on a linux server I have access to, so it must be something with my installation. Apologies for the confusion on my part. I'll debug things on my machine.

**Comment by eddelbuettel** [comment]
No need to apologize.  You may even have a newer version -- or then again maybe your `rmarkdown` and `pandoc` are out of sync.  This stuff can be finicky.  For example I appear to (still !!) be softlinking the one I get via RStudio  in over my distribution one:

```sh
edd@rob:~$ pandoc --version
pandoc 2.9.2.1
Compiled with pandoc-types 1.20, texmath 0.12.0.1, skylighting 0.8.3.2
Default user data directory: /home/edd/.local/share/pandoc or /home/edd/.pandoc
Copyright (C) 2006-2020 John MacFarlane
Web:  https://pandoc.org
This is free software; see the source for copying conditions.
There is no warranty, not even for merchantability or fitness
for a particular purpose.
edd@rob:~$ /usr/bin/pandoc --version
pandoc 2.5
Compiled with pandoc-types 1.17.5.4, texmath 0.11.2.2, skylighting 0.7.7
Default user data directory: /home/edd/.pandoc
Copyright (C) 2006-2018 John MacFarlane
Web:  http://pandoc.org
This is free software; see the source for copying conditions.
There is no warranty, not even for merchantability or fitness
for a particular purpose.
edd@rob:~$ 
```

**Comment by f-edwards** [comment]
Thanks again for the help. I think a TexLive update caused my problem. After addressing this issue, I'm able to compile with binb::metropolis

https://github.com/latex3/latex3/issues/753
