### ISSUE TITLE
New theme Monash (or MonashEBS) ?

### ISSUE THREAD

**Issue by eddelbuettel** [eddelbuettel/binb#9]
@robjhyndman has some snazzy Beamer theming here: https://github.com/robjhyndman/MonashEBSTemplates

Recent example:  https://github.com/robjhyndman/Writing-seminar/blob/master/Writing.pdf

When I glanced at the source it revealed itself as another Metropolis variant so it would fit here. Style file looks small and clean.  Have not checked if it needs additional fonts, but that would be a bridge we have crossed before :)

@izahn Thoughts?

@robjhyndman Any thoughts or concerns from your end?  Here in `binb` we mostly care about the Beamer side of things.

**Comment by izahn** [comment]
The theme is very nice. The title graphic is hard-coded, would be nice to make that configurable. I still need to do that for the IQSS theme also, so that clearly is not a prerequisite for inclusion in `binb`, but it would be nice. Other than that :+1:  from me.

**Comment by robjhyndman** [comment]
I'd be delighted to have that included in `binb`. The MonashBlue.sty file could be cleaned up a little. It contains a few things that I like, but that are not really theme-related. The default font is loaded with `\usepackage{bera}` which is a standard LaTeX package. Do you want a PR?

It would be good to make both Monash and IQSS more useful for other institutions. That probably means giving two versions of the title graphics, with a switching option in the yaml.

**Comment by eddelbuettel** [comment]
Ok -- I just checked and I can render MonashEBS Beamer just fine (based your package).

Slides in that look a little different than from the recent 'writing' seminar. Is that what you were referring to with the desired cleanup?  It will probably be rather easy to integrate it into `binb` as-is as it already works with `rmarkdown` etc.  But is there a place where we can see the different styling option?  Or are those mostly one-offs in style files (been there, done that myself, ....) ?

**Comment by robjhyndman** [comment]
I tend to over-ride the bera font with carlito. I would make that the default (as I think it looks nicer), but some users have had trouble with the resulting pdf not printing properly. I think it is an embedding issue, but I can't replicate it on Ubuntu 18.04 with TeXLive. So I just made the default font bera to avoid hassles.

There's a bunch of definitions of new commands in MonashBlue.sty that I sometimes use, but are not required for the theme. I'll remove them and send you a PR.

**Comment by eddelbuettel** [comment]
Sure.  What we've done so far is 
1. make it feasible -- so we added some themes
2. have the skeleton be brief but representative
3. make the vignette longer

Here `iqss` is in a funny spot because the CRAN version still depends HARD on a font not everybody has.  So for Monash we could use the same trick by @izahn (and borrewed from Metropolis):  have a safe default, but a fancier override per YAML.  We can expose more options that way.

How does that sound?
